version: "3.8"
services:
  spoofy:
    container_name: Spoofy
    build:
      context: .
      dockerfile: Dockerfile
    secrets:
      - spotify-user
      - spotify-passwd
      - discord-token
    deploy:
      resources:
        limits:
          memory: 256MB

secrets:
  spotify-user:
    file: ./secrets/spotify-user
  spotify-passwd:
    file: ./secrets/spotify-passwd
  discord-token:
    file: ./secrets/discord-token
