version: "3.8"
services:
  spoofy:
    container_name: spoofy
    build:
      context: .
    secrets:
      - spotify-user
      - spotify-passwd
      - discord-token
    deploy:
      resources:
        limits:
          memory: 256MB

  redis:
    image: bitnami/redis:latest
    container_name: spoofy_redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '6379:6379'
    volumes:
      - ./spoofy-redis-data:/bitnami/redis/data

secrets:
  spotify-user:
    file: ./secrets/spotify-user
  spotify-passwd:
    file: ./secrets/spotify-passwd
  discord-token:
    file: ./secrets/discord-token
