deviceId = "" ### Device ID (40 chars, leave empty for random)  ###
deviceName = "Spoofy" ### Device name ###
deviceType = "CAST_AUDIO" ### Device type (COMPUTER, TABLET, SMARTPHONE, SPEAKER, TV, AVR, STB, AUDIO_DONGLE, GAME_CONSOLE, CAST_VIDEO, CAST_AUDIO, AUTOMOBILE, WEARABLE, UNKNOWN_SPOTIFY, CAR_THING, UNKNOWN) ###
logLevel = "INFO" ### Log level (OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL) ###
preferredLocale = "en" ### Preferred locale ###

[auth] ### Authentication ###
blob = "" # Spotify authentication blob Base64-encoded (BLOB only)
credentialsFile = "credentials.json" # Credentials file (JSON)
password = "" # Spotify password (USER_PASS only)
storeCredentials = false # Whether to store reusable credentials on disk (not a plain password)
strategy = "USER_PASS" # Strategy (USER_PASS, ZEROCONF, BLOB, FACEBOOK, STORED)
username = "" # Spotify username (BLOB, USER_PASS only)

[zeroconf] ### Zeroconf ###
interfaces = "" # Listen on these interfaces (comma separated list of names)
listenAll = true # Listen on all interfaces (overrides `zeroconf.interfaces`)
listenPort = -1 # Listen on this TCP port (`-1` for random)

[cache] ### Cache ###
dir = "./cache/" 
doCleanUp = true 
enabled = true # Cache enabled

[network] ### Network ###
connectionTimeout = 10 # If ping isn't received within this amount of seconds, reconnect

[preload] ### Preload ###
enabled = true # Preload enabled

[time] ### Time correction ###
manualCorrection = 0 # Manual time correction in millis
synchronizationMethod = "NTP" # Time synchronization method (NTP, PING, MELODY, MANUAL)

[player] ### Player ###
autoplayEnabled = false # Autoplay similar songs when your music ends
bypassSinkVolume = false # Whether librespot-java should ignore volume events, sink volume is set to the max
crossfadeDuration = 0 # Crossfade overlap time (in milliseconds)
enableNormalisation = true # Whether to apply the Spotify loudness normalisation
initialVolume = 65536 # Initial volume (0-65536)
localFilesPath = "" # Where librespot-java should search for local files
logAvailableMixers = true # Log available mixers
metadataPipe = "" # Output metadata in Shairport Sync format (https://github.com/mikebrady/shairport-sync-metadata-reader)
mixerSearchKeywords = "" # Mixer/backend search keywords (semicolon separated)
normalisationPregain = +3.0 # Normalisation pregain in decibels (loud at +6, normal at +3, quiet at -5)
output = "MIXER" # Audio output device (MIXER, PIPE, STDOUT, CUSTOM)
outputClass = "" # Audio output Java class name
pipe = "" # Output raw (signed) PCM to this file (`player.output` must be PIPE)
preferredAudioQuality = "VERY_HIGH" # Preferred audio quality (NORMAL, HIGH, VERY_HIGH)
releaseLineDelay = 20 # Release mixer line after set delay (in seconds)
retryOnChunkError = true # Whether the player should retry fetching a chuck if it fails
volumeSteps = 64 # Number of volume notches

[api] ### API ###
host = "0.0.0.0" # API listen interface (`api` module only)
port = 24879 # API port (`api` module only)

[proxy] ### Proxy ###
address = "" # The proxy hostname
auth = false # Whether authentication is enabled on the server
enabled = false # Whether the proxy is enabled
password = "" # Basic auth password
port = 0 # The proxy port
type = "HTTP" # The proxy type (HTTP, SOCKS)
username = "" # Basic auth username

[shell] ### Shell ###
enabled = false # Shell events enabled
executeWithBash = false # Execute the command with `bash -c`
onConnectionDropped = "" 
onConnectionEstablished = "" 
onContextChanged = "" 
onInactiveSession = "" 
onMetadataAvailable = "" 
onPanicState = "" 
onPlaybackEnded = "" 
onPlaybackPaused = "" 
onPlaybackResumed = "" 
onTrackChanged = "" 
onTrackSeeked = "" 
onVolumeChanged = ""
