name: Build and publish docker image

# Controls when the workflow will run
on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
    types: [build-publish]

jobs:
  build-publish:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    steps:
      - name: Login to ghcr registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Set version
        uses: dotnet/nbgv@v0.4
        id: nbgv
        with:
          setAllVars: false

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          context: .
          tags: |
            ghcr.io/twinki14/spoofy:latest
            ghcr.io/twinki14/spoofy:${{ steps.nbgv.outputs.SimpleVersion }}
